[tool.poetry]
name = "pytune_auth_common"
version = "1.2.9"
description = "Module commun pour la gestion d'authentification et de ratelimit dans PyTune"
authors = ["gabriel de fombelle <gabriel.de.fombelle@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.3"
fastapi = "*"
python-jose = "*"
redis = "*"
pydantic = "*"
cryptography = "*"
python-dotenv = "*"
starlette = "*"
tortoise-orm = "*"
requests = "*"

typing = "*"
aiohttp = "*"
colorama = "*"

# Dépendances internes
pytune_data = { git = "https://github.com/gdefombelle/pytune_data.git" }
pytune_helpers = { git = "https://github.com/gdefombelle/pytune_helpers.git" }
simple_logger = { git = "https://github.com/gdefombelle/simple_logger.git" }
pytune_configuration = { git = "https://github.com/gdefombelle/pytune_configuration.git" }
passlib = "^1.7.4"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
black = "^23.0"
mypy = "^1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
